repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        name: Ruff linter
        stages: [commit]
        args: [--fix]
        files: ^backend/
      - id: ruff-format
        name: Ruff formatter
        stages: [commit]
        files: ^backend/
